### ISSUE TITLE
Deprecation plan

### ISSUE THREAD

**Issue by kamiolszewski** [puppetlabs/Puppet.Dsc#105]
If the future plan is to deprecate dsc in favor of more current modules, can we publish communication publically? That way we can advise new customers to not use this module and make it clear that we are maintaining this module only for legacy customers to ease their migration.

**Comment by michaeltlombardi** [comment]
@binford2k and I have been discussing this, we definitely want to get a clearer communication out - but for right now it's worth noting at least that the `puppetlabs-dsc` module has been code-frozen for over a year and only got minor patches for a year prior to that; the DSC Resources vendored in it are _extremely_ out of date and cannot be updated due to technical limitations (which in part drove this project).

**Comment by DavidS** [comment]
see also internal thread: https://puppet.slack.com/archives/CF418R4BE/p1610543797462000

**Comment by michaeltlombardi** [comment]
The deprecation notice is drafted in an internal document, discussion about dissemination is underway.
