### ISSUE TITLE
Use custom pdk template

### ISSUE THREAD

**Issue by derek-robinson** [puppetlabs/Puppet.Dsc#117]
## Use Case
When building Puppetized DSC modules for internal use, we would like to point to our custom pdk template(s). There files in the default template we don't want and other files that we add to all of our repos. Adding the ability to do this with the template we already use would save time spent manually adding/removing as well as let us fully automate the process.

## Describe the Solution You Would Like
We would like an additional parameter in the command to let us point to our pdk template or however it's best implemented.

## Describe Alternatives You've Considered
As an alternative, we've thought about manually tweaking the Puppet.Dsc module to point to our template. However, this would have to be redone on every module update and require us to either fork the module internally or only run it from certain servers to get the desired effect.

**Comment by michaeltlombardi** [comment]
It _sounds_ to me like the solution to this would be to:

1. Add a `$TemplateUrl` parameter to the [`Initialize-PuppetModule` internal function](https://github.com/puppetlabs/Puppet.Dsc/blob/main/src/internal/functions/Initialize-PuppetModule.ps1) which already uses the template url but hard codes to the puppetlabs/pdk-templates.
2. Ensure that a `$PdkTemplateUrl` parameter is added to [`New-PuppetDscModule`]() which can allow the passthru of that setting to the `Initialize-PuppetModule` command.

If you're open to implementing this feature, I'd be happy to work with you on it (esp getting it tested and merged). Otherwise we'll put it on our todo list but it will likely go in the next milestone.
