### ISSUE TITLE
Add handling for 'parameter' attributes

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/Puppet.Dsc#81]
## Use Case
Some properties passed to DSC can be _set_ but not _read_ back from the system - things like `Force` flags and credentials (see #60 for complications regarding credentials properties). This causes flapping where they are _specified in a manifest_ but never found, which should be resolved.

## Describe the Solution You Would Like
Properties which are known to be parameter-type attributes should be marked as such. Currently there is no way to tell if a DSC Resource property is write-only; the `Write` attribute is applied to all properties which are not required, key, or read-only and does not distinguish between write-only and write-and-retrieve properties. This information is not available via the MOF, AST parsing, or introspecting the CIM instance.

Instead, a short list of `parameter-likely` property names should be kept and used to do a best-effort on this problem until such a time as DSC supports this distinction natively:

- `Force` - this keyword implies a set-time decision
- `Purge` - this keyword implies a set-time decision
- `*Credential` - anything which specifies a credential object likely cannot be read from the target system.

This information should be kept in a `Test-DscResourcePropertyParameterStatus` internal function, referenced in `Get-TypeParameterContent`, where a parameter gets the `:parameter` behavior if necessary.

## Acceptance Criteria:

- [x] New function `Test-DscResourcePropertyParameterStatus` exists and has unit tests
- [x] New acceptance test which validates use of `dsc_psdscrunascredential` without flapping or warnings.
- [x] When puppetizing `PowerShellGet`, the generated `dsc_psmodule` resource type has the `dsc_force` and `dsc_psdscrunascredential` attributes marked as parameters.
- [x] Those parameters can be specified in a sample manifest without canonicalization errors
- [x] Those parameters can be specified in a sample manifest without flapping

**Comment by gaelcolas** [comment]
Usually, those type of parameters are to be avoided, but it's true that we're probably using them in Resources every now and then.
I can think of times where we want a resource to be exclusive (remove everything not specified in the resource) instead of additive.
Depending on the resource and its context, it may have a different name.
Those are point in time (when you do a Get, a Test, or a Set), so they should be `[DscProperty(Write)]`, so maybe that's not what you're really after, but they don't always reflect the state of the system (more about how the resource should behave).

One that could be in this approach is `RestoreFromRecycleBin` from ActiveDirectoryDsc, or also `EnabledOnCreation`.
https://github.com/dsccommunity/ActiveDirectoryDsc/wiki/ADComputer

If that's what you're after, the best approach might be to:
 - create a class property attribute that we'll add to [DscResource.Common](https://github.com/dsccommunity/DscResource.Common)
 - update resources in DSC Community to use that new attribute when we move to Class Based DSC Resources
 - Ask the PS Team to add this Attribute to DscProperty attribute

Doing so would help you flag those attributes for puppet.

**Comment by michaeltlombardi** [comment]
I'll add those property names to the list for now and file that issue in [DscResource.Common](https://github.com/dsccommunity/DscResource.Common) and the PSDesiredStateConfiguration repo - I tried several different ways to introspect on DSC Resources to determine parameter status but the `Write` key is _also_ used by properties that _can_ be read back from the system. We do have #80 for handling read-only attributes as well.

I think it would be useful to DSC authors/users and Puppet users alike to have these properties more accurately and explicitly described instead of needing to be inferred from implementation.
